#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case "$1" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/lib/aarch64-linux-gnu/libfido2.so.1
copy_exec /usr/lib/aarch64-linux-gnu/cryptsetup/libcryptsetup-token-systemd-fido2.so

if [ -f /lib/udev/rules.d/60-fido-id.rules ]; then
	copy_file rule "/lib/udev/rules.d/60-fido-id.rules"
fi
